Repository zjedi/hugo-scroll, pull requests merged in 2023-03, with the labels that each got.

#96 Add icon on defaul single view infront of back-to-homepage link
  layouts/_default/single.html
Labels: UX

#99 external links - external links in main menu
  layouts/index.html
Labels: enhancement

#81 Optimize Theme with Assets Bundles and fixes missing lang attribute in HTML
  assets/css/fonts.css
  assets/css/fork-awesome.css
  assets/css/normalize.css
  assets/css/screen.css
  assets/js/icons.js
  assets/js/index.js
  assets/js/jquery-3.6.3.min.js
  layouts/_default/baseof.html
  layouts/_default/single.html
  layouts/partials/head.html
  static/fonts/forkawesome-webfont.eot
  static/fonts/forkawesome-webfont.svg
  static/fonts/forkawesome-webfont.ttf
  static/fonts/forkawesome-webfont.woff
  static/fonts/forkawesome-webfont.woff2
  static/fork-awesome/LICENSES
  static/fork-awesome/README.md
  static/fork-awesome/css/fork-awesome.min.css
  static/fork-awesome/css/fork-awesome.min.css.map
  static/fork-awesome/less/animated.less
  static/fork-awesome/less/bordered-pulled.less
  static/fork-awesome/less/core.less
  static/fork-awesome/less/fixed-width.less
  static/fork-awesome/less/fork-awesome.less
  static/fork-awesome/less/icons.less
  static/fork-awesome/less/larger.less
  static/fork-awesome/less/list.less
  static/fork-awesome/less/mixins.less
  static/fork-awesome/less/path.less
  static/fork-awesome/less/rotated-flipped.less
  static/fork-awesome/less/screen-reader.less
  static/fork-awesome/less/stacked.less
  static/fork-awesome/less/v5-compat.less
  static/fork-awesome/less/variables.less
  static/fork-awesome/scss/_animated.scss
  static/fork-awesome/scss/_bordered-pulled.scss
  static/fork-awesome/scss/_core.scss
  static/fork-awesome/scss/_fixed-width.scss
  static/fork-awesome/scss/_functions.scss
  static/fork-awesome/scss/_icons.scss
  static/fork-awesome/scss/_larger.scss
  static/fork-awesome/scss/_list.scss
  static/fork-awesome/scss/_mixins.scss
  static/fork-awesome/scss/_path.scss
  static/fork-awesome/scss/_rotated-flipped.scss
  static/fork-awesome/scss/_screen-reader.scss
  static/fork-awesome/scss/_stacked.scss
  static/fork-awesome/scss/_variables.scss
  static/fork-awesome/scss/fork-awesome.scss
  static/js/jquery-3.6.0.min.js
  theme.toml
Labels: dependencies, priority-high, optimization

#92 chore: Update `normalize.css` to version 8.0.1
  assets/css/normalize.css
Labels: dependencies, priority-high

#97 Remove unused icons font and styles, use font awesome instead
  assets/css/screen.css
  static/fonts/icons.dev.svg
  static/fonts/icons.eot
  static/fonts/icons.svg
  static/fonts/icons.ttf
  static/fonts/icons.woff
Labels: optimization

#45 #41: Override button and menu item text
  archetypes/homepage.md
  assets/js/index.js
  exampleSite/content/homepage/services.md
  layouts/index.html
Labels: enhancement
